name: Netology AHJ

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - run: cd frontend && npm install
      - run: cd frontend && npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - run: cd frontend && npm install
      
      - name: Run E2E Puppeteer tests
        run: |
          cd frontend
          # Убиваем всё, что заняло порт
          sudo fuser -k 8080/tcp || true
          
          # Собираем проект
          npm run build
          
          # Запускаем сервер на папке dist и просто оставляем его работать
          npx serve dist -l 8080 &
          sleep 5 # Даем серверу 5 секунд на запуск
        env:
          CI: true

  build:
    needs: [eslint, test]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.14.0
      - run: cd frontend && npm install
      - run: cd frontend && npm run build
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Указываем путь к папке dist внутри фронтенда
          path: 'frontend/dist'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4